[ecos]
user = "admin"
password = "password"
base_url = "https://api-ecos-au.weiheng-tech.com/api"

[app]
deviceId = "123456"
checkInterval = 600
chargeUseMode = 0
minCapacity = 10
maxFeedIn = 100
dischargeToGridFlag = 0
chargingList = []
dischargingList = []
epsBatteryMin = 10
